server:
  port: 9081
  servlet:
    context-path: /target-service

spring:
  application:
    name: target-service
  config:
    import: optional:file:./targetservice/.env[.properties]
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:alisa/smallokr/mapper/xml/*.xml
