server:
  port: 8083
spring:
  application:
    name: trace-service
  config:
    import:
      - optional:file:./smallokr_server/traceservice/.env[.properties]
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:alisa/smallokr/mapper/xml/*.xml
