spring:
  data:
    redis:
      host: ${REDIS_HOST} # Redis服务器地址
      port: ${REDIS_PORT} # 默认端口
      password: ${REDIS_PASSWORD} # 如果有密码
      database: ${REDIS_DB} # 默认DB索引
      # lettuce:
      #   pool:
      #     max-active: 8      # 最大连接数
      #     max-idle: 4        # 最大空闲连接
      #     min-idle: 1        # 最小空闲连接
      #     max-wait: 2000ms   # 获取连接最大等待时间
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
        namespace: ${NACOS_NAMESPACE}
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mail:
    host: ${MAIL_HOST} # 邮件服务器地址，例如 smtp.qq.com
    port: ${MAIL_PORT} # 邮件服务器端口，例如 465
    username: ${MAIL_USERNAME} # 你的 Outlook 邮箱
    password: ${MAIL_PASSWORD} # 邮箱密码或应用密码
    protocol: ${MAIL_PROTOCOL} # 邮件协议
    properties:
      mail:
        smtp:
          auth: true # 启用认证
          starttls.enable: true # 启用 TLS
          ssl.enable: true # 启用 SSL 加密
