server:
  port: 8084
spring:
  application:
    name: user-service
  config:
    import: optional:file:./userservice/.env[.properties]
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:alisa/smallokr/mapper/xml/*.xml
jwt:
  secret: ${JWT_SECRET}
